"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import mimetypes
import socket
import sys
import environ
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Initialize environment variables
env = environ.Env(DEBUG=(bool, False))

# Load environment variables.
# Default to local development settings unless explicitly set to production.
production_env = BASE_DIR / ".envs/.production/.django"
local_env = BASE_DIR / ".envs/.local/.django"
environment = os.getenv("DJANGO_ENV", "local").lower()

if environment == "production" and production_env.exists():
    env.read_env(production_env)
elif local_env.exists():
    env.read_env(local_env)
elif production_env.exists():
    env.read_env(production_env)
else:
    # Fallback for basic development without env files
    pass

SECRET_KEY = env("DJANGO_SECRET_KEY", default="django-insecure-development-key-change-in-production")
DEBUG = env.bool("DJANGO_DEBUG", default=True)
ALLOWED_HOSTS = env.list("DJANGO_ALLOWED_HOSTS", default=["localhost", "127.0.0.1"])
CSRF_TRUSTED_ORIGINS = env.list("DJANGO_CSRF_TRUSTED_ORIGINS", default=[])
TESTING = "test" in sys.argv or "PYTEST_VERSION" in os.environ

# Local dev: always allow local hosts on the common debug ports.
if environment != "production":
    _local_hosts = {"localhost", "127.0.0.1"}
    ALLOWED_HOSTS = list(_local_hosts | set(ALLOWED_HOSTS))
    _local_csrf = {
        "http://127.0.0.1:8000",
        "http://localhost:8000",
        "http://127.0.0.1:9000",
        "http://localhost:9000",
    }
    CSRF_TRUSTED_ORIGINS = list(_local_csrf | set(CSRF_TRUSTED_ORIGINS))
    if not DEBUG:
        DEBUG = True

# Windows can sometimes serve debug_toolbar JavaScript with the wrong MIME type.
mimetypes.add_type("application/javascript", ".js", True)

ENABLE_DEBUG_TOOLBAR = DEBUG and environment != "production" and not TESTING


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
]

if ENABLE_DEBUG_TOOLBAR:
    INSTALLED_APPS.append("debug_toolbar")

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

if ENABLE_DEBUG_TOOLBAR:
    MIDDLEWARE.insert(2, "debug_toolbar.middleware.DebugToolbarMiddleware")

INTERNAL_IPS = [
    "127.0.0.1",
    "::1",
]

if ENABLE_DEBUG_TOOLBAR:
    try:
        hostname, _, ips = socket.gethostbyname_ex(socket.gethostname())
    except socket.gaierror:
        ips = []
    INTERNAL_IPS += [ip.rsplit(".", 1)[0] + ".1" for ip in ips]

ROOT_URLCONF = 'config.urls'

# ===== DJANGO SECURITY SETTINGS =====
if not DEBUG:
    # If behind Nginx/HTTPS
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    
    SECURE_SSL_REDIRECT = True
    
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    
    SECURE_HSTS_SECONDS = 3600  # 1 hour first (increase later)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = False  # keep False until you're 100% sure
    
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = "DENY"
    SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.template.context_processors.debug',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# WhiteNoise configuration for better caching
WHITENOISE_MAX_AGE = 31536000  # 1 year for hashed assets
